# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui',
# licensing of 'ui_main_window.ui' applies.
#
# Created: Mon Sep 23 10:28:35 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 532)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.processesListView = QtWidgets.QListView(self.centralwidget)
        self.processesListView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.processesListView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.processesListView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.processesListView.setObjectName("processesListView")
        self.horizontalLayout_4.addWidget(self.processesListView)
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.fileStatistics = QtWidgets.QWidget()
        self.fileStatistics.setObjectName("fileStatistics")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fileStatistics)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.fileStatistics)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxBin = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxBin.setObjectName("checkBoxBin")
        self.horizontalLayout.addWidget(self.checkBoxBin)
        self.checkBoxDev = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxDev.setObjectName("checkBoxDev")
        self.horizontalLayout.addWidget(self.checkBoxDev)
        self.checkBoxEtc = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxEtc.setObjectName("checkBoxEtc")
        self.horizontalLayout.addWidget(self.checkBoxEtc)
        self.checkBoxHome = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxHome.setObjectName("checkBoxHome")
        self.horizontalLayout.addWidget(self.checkBoxHome)
        self.checkBoxOpt = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxOpt.setObjectName("checkBoxOpt")
        self.horizontalLayout.addWidget(self.checkBoxOpt)
        self.checkBoxProc = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxProc.setObjectName("checkBoxProc")
        self.horizontalLayout.addWidget(self.checkBoxProc)
        self.checkBoxRun = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxRun.setObjectName("checkBoxRun")
        self.horizontalLayout.addWidget(self.checkBoxRun)
        self.checkBoxSys = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxSys.setObjectName("checkBoxSys")
        self.horizontalLayout.addWidget(self.checkBoxSys)
        self.checkBoxTmp = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxTmp.setObjectName("checkBoxTmp")
        self.horizontalLayout.addWidget(self.checkBoxTmp)
        self.checkBoxUsr = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxUsr.setObjectName("checkBoxUsr")
        self.horizontalLayout.addWidget(self.checkBoxUsr)
        self.checkBoxVar = QtWidgets.QCheckBox(self.fileStatistics)
        self.checkBoxVar.setObjectName("checkBoxVar")
        self.horizontalLayout.addWidget(self.checkBoxVar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.filestatsLineEdit = QtWidgets.QLineEdit(self.fileStatistics)
        self.filestatsLineEdit.setObjectName("filestatsLineEdit")
        self.verticalLayout.addWidget(self.filestatsLineEdit)
        self.filestatsTableView = QtWidgets.QTableView(self.fileStatistics)
        self.filestatsTableView.setSortingEnabled(True)
        self.filestatsTableView.setObjectName("filestatsTableView")
        self.verticalLayout.addWidget(self.filestatsTableView)
        self.tabs.addTab(self.fileStatistics, "")
        self.syscalls = QtWidgets.QWidget()
        self.syscalls.setObjectName("syscalls")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.syscalls)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.syscallsLineEdit = QtWidgets.QLineEdit(self.syscalls)
        self.syscallsLineEdit.setObjectName("syscallsLineEdit")
        self.verticalLayout_2.addWidget(self.syscallsLineEdit)
        self.syscallsTableView = QtWidgets.QTableView(self.syscalls)
        self.syscallsTableView.setSortingEnabled(True)
        self.syscallsTableView.setObjectName("syscallsTableView")
        self.verticalLayout_2.addWidget(self.syscallsTableView)
        self.tabs.addTab(self.syscalls, "")
        self.horizontalLayout_4.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 32))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpenRecent = QtWidgets.QAction(MainWindow)
        self.actionOpenRecent.setObjectName("actionOpenRecent")
        self.actionColumns = QtWidgets.QAction(MainWindow)
        self.actionColumns.setObjectName("actionColumns")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "iotrace-GUI", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "<u>Filter:</u>", None, -1))
        self.checkBoxBin.setText(QtWidgets.QApplication.translate("MainWindow", "/bin", None, -1))
        self.checkBoxDev.setText(QtWidgets.QApplication.translate("MainWindow", "/dev", None, -1))
        self.checkBoxEtc.setText(QtWidgets.QApplication.translate("MainWindow", "/etc", None, -1))
        self.checkBoxHome.setText(QtWidgets.QApplication.translate("MainWindow", "/home", None, -1))
        self.checkBoxOpt.setText(QtWidgets.QApplication.translate("MainWindow", "/opt", None, -1))
        self.checkBoxProc.setText(QtWidgets.QApplication.translate("MainWindow", "/proc", None, -1))
        self.checkBoxRun.setText(QtWidgets.QApplication.translate("MainWindow", "/run", None, -1))
        self.checkBoxSys.setText(QtWidgets.QApplication.translate("MainWindow", "/sys", None, -1))
        self.checkBoxTmp.setText(QtWidgets.QApplication.translate("MainWindow", "/tmp", None, -1))
        self.checkBoxUsr.setText(QtWidgets.QApplication.translate("MainWindow", "/usr", None, -1))
        self.checkBoxVar.setText(QtWidgets.QApplication.translate("MainWindow", "/var", None, -1))
        self.filestatsLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Filename filter (Perl regex)", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.fileStatistics), QtWidgets.QApplication.translate("MainWindow", "File Statistics", None, -1))
        self.syscallsLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Syscall filter (Perl regex)", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.syscalls), QtWidgets.QApplication.translate("MainWindow", "Unconsidered Syscalls", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionOpenRecent.setText(QtWidgets.QApplication.translate("MainWindow", "Open Recent", None, -1))
        self.actionColumns.setText(QtWidgets.QApplication.translate("MainWindow", "Columns", None, -1))
        self.actionAboutQt.setText(QtWidgets.QApplication.translate("MainWindow", "About Qt", None, -1))

